package GUI;


import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Catalogo extends javax.swing.JFrame {

    /**
     * Creates new form Catalogo
     */
    public Catalogo() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TablaVehiculos = new javax.swing.JTable();
        jPanelRenta4 = new javax.swing.JPanel();
        jLabelRenta4 = new javax.swing.JLabel();
        jComboRentaMes4 = new javax.swing.JComboBox<>();
        jComboRentaDia4 = new javax.swing.JComboBox<>();
        jComboRentaAnio4 = new javax.swing.JComboBox<>();
        jLabelDevolucion4 = new javax.swing.JLabel();
        jComboDevoAnio4 = new javax.swing.JComboBox<>();
        jComboDevoMes4 = new javax.swing.JComboBox<>();
        jComboDevoDia4 = new javax.swing.JComboBox<>();
        BotonAlquilar4 = new javax.swing.JButton();
        jLabelTranscurridos4 = new javax.swing.JLabel();
        jLabelCosto4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Price", "Quality", "ProviderCOde"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaVehiculos.setCellSelectionEnabled(true);
        TablaVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaVehiculosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaVehiculos);
        TablaVehiculos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanelRenta4.setBackground(new java.awt.Color(153, 153, 153));

        jLabelRenta4.setText("Codigo:");
        jLabelRenta4.setToolTipText("");

        jComboRentaMes4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboRentaMes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboRentaMes4ActionPerformed(evt);
            }
        });

       

        jComboRentaAnio4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        jComboRentaAnio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboRentaAnio4ActionPerformed(evt);
            }
        });

        jLabelDevolucion4.setText("Fecha de devolución:");
        jLabelDevolucion4.setToolTipText("");

        jComboDevoAnio4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        jComboDevoAnio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDevoAnio4ActionPerformed(evt);
            }
        });

        jComboDevoMes4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboDevoMes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDevoMes4ActionPerformed(evt);
            }
        });

        jComboDevoDia4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDevoDia4ActionPerformed(evt);
            }
        });

        BotonAlquilar4.setText("Buscar");
        BotonAlquilar4.setEnabled(false);
        BotonAlquilar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAlquilar4ActionPerformed(evt);
            }
        });

        jLabelTranscurridos4.setText(" ");

        jLabelCosto4.setText(" ");

        javax.swing.GroupLayout jPanelRenta4Layout = new javax.swing.GroupLayout(jPanelRenta4);
        jPanelRenta4.setLayout(jPanelRenta4Layout);
        jPanelRenta4Layout.setHorizontalGroup(
            jPanelRenta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRenta4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRenta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelRenta4Layout.createSequentialGroup()
                        .addGap(0, 557, Short.MAX_VALUE)
                        .addComponent(jLabelCosto4))
                    .addGroup(jPanelRenta4Layout.createSequentialGroup()
                        .addGroup(jPanelRenta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelRenta4Layout.createSequentialGroup()
                                .addComponent(jLabelRenta4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboRentaAnio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboRentaMes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                
                                .addComponent(jLabelDevolucion4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboDevoAnio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboDevoMes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboDevoDia4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                        .addGroup(jPanelRenta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonAlquilar4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTranscurridos4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanelRenta4Layout.setVerticalGroup(
            jPanelRenta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRenta4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRenta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRenta4)
                    .addComponent(jComboRentaMes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    
                    .addComponent(jComboRentaAnio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAlquilar4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRenta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDevolucion4)
                    .addComponent(jComboDevoAnio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboDevoMes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboDevoDia4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTranscurridos4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCosto4)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelRenta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRenta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaVehiculosMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TablaVehiculosMouseClicked

    private void jComboRentaMes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboRentaMes4ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboRentaMes4ActionPerformed

    private void jComboRentaDia4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboRentaDia4ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboRentaDia4ActionPerformed

    private void jComboRentaAnio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboRentaAnio4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboRentaAnio4ActionPerformed

    private void jComboDevoAnio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDevoAnio4ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboDevoAnio4ActionPerformed

    private void jComboDevoMes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDevoMes4ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboDevoMes4ActionPerformed

    private void jComboDevoDia4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDevoDia4ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboDevoDia4ActionPerformed

    private void BotonAlquilar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAlquilar4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_BotonAlquilar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAlquilar;
    private javax.swing.JButton BotonAlquilar1;
    private javax.swing.JButton BotonAlquilar2;
    private javax.swing.JButton BotonAlquilar3;
    private javax.swing.JButton BotonAlquilar4;
    private javax.swing.JTable TablaVehiculos;
    private javax.swing.JComboBox<String> jComboDevoAnio;
    private javax.swing.JComboBox<String> jComboDevoAnio1;
    private javax.swing.JComboBox<String> jComboDevoAnio2;
    private javax.swing.JComboBox<String> jComboDevoAnio3;
    private javax.swing.JComboBox<String> jComboDevoAnio4;
    private javax.swing.JComboBox<String> jComboDevoDia;
    private javax.swing.JComboBox<String> jComboDevoDia1;
    private javax.swing.JComboBox<String> jComboDevoDia2;
    private javax.swing.JComboBox<String> jComboDevoDia3;
    private javax.swing.JComboBox<String> jComboDevoDia4;
    private javax.swing.JComboBox<String> jComboDevoMes;
    private javax.swing.JComboBox<String> jComboDevoMes1;
    private javax.swing.JComboBox<String> jComboDevoMes2;
    private javax.swing.JComboBox<String> jComboDevoMes3;
    private javax.swing.JComboBox<String> jComboDevoMes4;
    private javax.swing.JComboBox<String> jComboRentaAnio;
    private javax.swing.JComboBox<String> jComboRentaAnio1;
    private javax.swing.JComboBox<String> jComboRentaAnio2;
    private javax.swing.JComboBox<String> jComboRentaAnio3;
    private javax.swing.JComboBox<String> jComboRentaAnio4;
    private javax.swing.JComboBox<String> jComboRentaDia;
    private javax.swing.JComboBox<String> jComboRentaDia1;
    private javax.swing.JComboBox<String> jComboRentaDia2;
    private javax.swing.JComboBox<String> jComboRentaDia3;
    private javax.swing.JComboBox<String> jComboRentaMes;
    private javax.swing.JComboBox<String> jComboRentaMes1;
    private javax.swing.JComboBox<String> jComboRentaMes2;
    private javax.swing.JComboBox<String> jComboRentaMes3;
    private javax.swing.JComboBox<String> jComboRentaMes4;
    private javax.swing.JLabel jLabelCosto;
    private javax.swing.JLabel jLabelCosto1;
    private javax.swing.JLabel jLabelCosto2;
    private javax.swing.JLabel jLabelCosto3;
    private javax.swing.JLabel jLabelCosto4;
    private javax.swing.JLabel jLabelDevolucion;
    private javax.swing.JLabel jLabelDevolucion1;
    private javax.swing.JLabel jLabelDevolucion2;
    private javax.swing.JLabel jLabelDevolucion3;
    private javax.swing.JLabel jLabelDevolucion4;
    private javax.swing.JLabel jLabelRenta;
    private javax.swing.JLabel jLabelRenta1;
    private javax.swing.JLabel jLabelRenta2;
    private javax.swing.JLabel jLabelRenta3;
    private javax.swing.JLabel jLabelRenta4;
    private javax.swing.JLabel jLabelTranscurridos;
    private javax.swing.JLabel jLabelTranscurridos1;
    private javax.swing.JLabel jLabelTranscurridos2;
    private javax.swing.JLabel jLabelTranscurridos3;
    private javax.swing.JLabel jLabelTranscurridos4;
    private javax.swing.JPanel jPanelRenta;
    private javax.swing.JPanel jPanelRenta1;
    private javax.swing.JPanel jPanelRenta2;
    private javax.swing.JPanel jPanelRenta3;
    private javax.swing.JPanel jPanelRenta4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}